[package]
name = "net_game_test"
version = "0.1.0"
authors = ["Nils Olsson <nilso@enosis.net>"]
edition = "2018"

[dependencies]
clap = { version = "2.33", features = ["yaml"] }
rustyline = "4.1"
laminar = "0.2"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.1"
crossbeam-channel = "0.3"